# Generated by Django 5.1.6 on 2025-04-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiprocketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.BigIntegerField()),
                ('shipment_id', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('awb_code', models.CharField(max_length=50)),
                ('courier_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderedcart')),
            ],
        ),
    ]
