# Generated by Django 5.1.6 on 2025-04-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
        ('Orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprocketorder',
            name='status_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
    ]
