# Generated by Django 5.1.6 on 2025-04-26 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_shiprocketorder_status_code_and_more'),
        ('Orders', '0009_alter_orderhistory_additional_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprocketorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
    ]
