# Generated by Django 5.1.6 on 2025-04-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_alter_shiprocketorder_order'),
        ('Orders', '0013_alter_cart_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiprocketorder',
            name='order',
        ),
        migrations.AddField(
            model_name='shiprocketorder',
            name='orderH',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Orders.orderhistory'),
            preserve_default=False,
        ),
    ]
