# Generated by Django 5.1.6 on 2025-04-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0006_alter_shiprocketorder_orderh'),
        ('Orders', '0013_alter_cart_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprocketorder',
            name='orderH',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderhistory'),
        ),
    ]
