events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;

  server {
    listen 80;

    # ----- Static & Media from Docker named volumes -----
    location /static/ {
      alias /static/;                  # from staticfiles volume
      expires 7d;
      add_header Cache-Control "public";
    }

    location /media/ {
      alias /media/;                   # from mediafiles volume
      expires 7d;
      add_header Cache-Control "public, max-age=604800, immutable";
    }

    # ----- App proxy -----
    location / {
      proxy_pass http://django-web:8000;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      client_max_body_size 20m;        # allow uploads
      proxy_read_timeout 120;
      proxy_connect_timeout 60;
      proxy_send_timeout 120;
    }
  }
}
