# Generated by Django 5.1.6 on 2025-03-20 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojos',
            name='display_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
