# Generated by Django 5.1.6 on 2025-03-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0003_alter_pojos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojos',
            name='category',
            field=models.ForeignKey(default='Jewelry', on_delete=django.db.models.deletion.CASCADE, related_name='pojos', to='POJOS.category'),
            preserve_default=False,
        ),
    ]
