# Generated by Django 5.1.6 on 2025-03-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0004_alter_pojos_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOfBangles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfBracelets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfChains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfEarRings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfFingerRings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfImportedJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfNecklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfNoseRings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfOneGramGoldenJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfPendants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfWeddingJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POJOS.pojos')),
            ],
        ),
    ]
