# Generated by Django 5.1.6 on 2025-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0006_remove_bestofbangles_pojos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestofbangles',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Bangles'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofbracelets',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Bracelets'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofchains',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Chains'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofearrings',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Ear Rings'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestoffingerrings',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Finger Rings'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofimportedjewellery',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Imported jewellery'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofnecklace',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Necklace'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofnoserings',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Nose Rings'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofonegramgoldenjewellery',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'One Gram Golden Jewellery'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofpendants',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Pendants'}, to='POJOS.pojos'),
        ),
        migrations.AlterField(
            model_name='bestofweddingjewellery',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Wedding Jewellery'}, to='POJOS.pojos'),
        ),
    ]
