# Generated by Django 5.1.6 on 2025-03-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0007_alter_bestofbangles_pojos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestofimportedjewellery',
            name='pojos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Imported Jewellery'}, to='POJOS.pojos'),
        ),
    ]
