# Generated by Django 5.1.6 on 2025-03-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0009_pojos_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojos',
            name='pojo_id',
        ),
        migrations.AlterField(
            model_name='pojos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocos', to='POJOS.category'),
        ),
        migrations.AlterField(
            model_name='pojos',
            name='sku',
            field=models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
