# Generated by Django 5.1.6 on 2025-03-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0010_remove_pojos_pojo_id_alter_pojos_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pojos', to='POJOS.category'),
        ),
    ]
