# Generated by Django 5.1.6 on 2025-03-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0011_alter_pojos_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestofbangles',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofbracelets',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofchains',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofearrings',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestoffingerrings',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofimportedjewellery',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofnecklace',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofnoserings',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofonegramgoldenjewellery',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofpendants',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofweddingjewellery',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestsellers',
            old_name='pojos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='featureproducts',
            old_name='pojos',
            new_name='objs',
        ),
    ]
