# Generated by Django 5.1.6 on 2025-05-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POJOS', '0012_rename_pojos_bestofbangles_objs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='verified_user',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pojos_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
