# Generated by Django 5.1.6 on 2025-03-11 06:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocos',
            options={},
        ),
        migrations.RenameField(
            model_name='pocos',
            old_name='image',
            new_name='display_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='POCOS.pocos')),
            ],
        ),
    ]
