# Generated by Django 5.1.6 on 2025-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocos',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
            preserve_default=False,
        ),
    ]
