# Generated by Django 5.1.6 on 2025-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0002_pocos_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
