# Generated by Django 5.1.6 on 2025-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0002_alter_pocos_options_rename_image_pocos_display_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
