# Generated by Django 5.1.6 on 2025-03-13 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0003_pocos_poco_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='PocoImage',
        ),
        migrations.RenameField(
            model_name='pocoimage',
            old_name='product',
            new_name='poco',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pocos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocos', to='POCOS.category'),
        ),
        migrations.AlterField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pocos',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='POCOS.pocos')),
            ],
        ),
    ]
