# Generated by Django 5.1.6 on 2025-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0004_rename_productimage_pocoimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
