# Generated by Django 5.1.6 on 2025-03-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0004_alter_pocos_display_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOfBodyCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfColorCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfFragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfHairCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfImportedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestOfSkinCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POCOS.pocos')),
            ],
        ),
    ]
