# Generated by Django 5.1.6 on 2025-03-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0005_alter_pocos_poco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocos',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
