# Generated by Django 5.1.6 on 2025-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0005_bestofbodycare_bestofcolorcosmetic_bestoffragrance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestofbodycare',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestofcolorcosmetic',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestoffragrance',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestofhaircare',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestofimportedproducts',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestofskincare',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='bestsellers',
            name='pocos',
        ),
        migrations.RemoveField(
            model_name='featureproducts',
            name='pocos',
        ),
        migrations.AddField(
            model_name='bestofbodycare',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestofcolorcosmetic',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestoffragrance',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestofhaircare',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestofimportedproducts',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestofskincare',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
        migrations.AddField(
            model_name='featureproducts',
            name='pocos',
            field=models.ManyToManyField(to='POCOS.pocos'),
        ),
    ]
