# Generated by Django 5.1.6 on 2025-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0006_pocos_size_review_verified_user_alter_pocos_poco_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocos',
            name='id',
        ),
        migrations.AlterField(
            model_name='pocos',
            name='poco_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
