# Generated by Django 5.1.6 on 2025-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0006_remove_bestofbodycare_pocos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestofbodycare',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Bodycare'}, to='POCOS.pocos'),
        ),
        migrations.AlterField(
            model_name='bestofcolorcosmetic',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Color Cosmetics'}, to='POCOS.pocos'),
        ),
        migrations.AlterField(
            model_name='bestoffragrance',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Fragrances'}, to='POCOS.pocos'),
        ),
        migrations.AlterField(
            model_name='bestofhaircare',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Haircare'}, to='POCOS.pocos'),
        ),
        migrations.AlterField(
            model_name='bestofimportedproducts',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Imported Products'}, to='POCOS.pocos'),
        ),
        migrations.AlterField(
            model_name='bestofskincare',
            name='pocos',
            field=models.ManyToManyField(limit_choices_to={'category': 'Skincare'}, to='POCOS.pocos'),
        ),
    ]
