# Generated by Django 5.1.6 on 2025-03-15 11:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0007_remove_pocos_id_alter_pocos_poco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocos',
            name='display_image',
            field=cloudinary.models.CloudinaryField(default='pocos/display/elfpvad5o7iqzjnipqqa', max_length=255, verbose_name='image'),
        ),
    ]
