# Generated by Django 5.1.6 on 2025-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0007_alter_bestofbodycare_pocos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocos',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
