# Generated by Django 5.1.6 on 2025-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0008_pocos_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocos',
            name='poco_id',
        ),
        migrations.AlterField(
            model_name='pocos',
            name='sku',
            field=models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
