# Generated by Django 5.1.6 on 2025-03-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0009_remove_pocos_poco_id_alter_pocos_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestofbodycare',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofcolorcosmetic',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestoffragrance',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofhaircare',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofimportedproducts',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestofskincare',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='bestsellers',
            old_name='pocos',
            new_name='objs',
        ),
        migrations.RenameField(
            model_name='featureproducts',
            old_name='pocos',
            new_name='objs',
        ),
    ]
