# Generated by Django 5.1.6 on 2025-05-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POCOS', '0010_rename_pocos_bestofbodycare_objs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='verified_user',
        ),
    ]
