# Generated by Django 5.1.6 on 2025-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='name',
            field=models.CharField(default='anish', max_length=100),
            preserve_default=False,
        ),
    ]
