# Generated by Django 5.1.6 on 2025-03-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_verification_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
