# Generated by Django 5.1.6 on 2025-03-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_delete_useractivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='name',
        ),
    ]
