# Generated by Django 5.1.6 on 2025-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
