# Generated by Django 5.1.6 on 2025-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_useraccount_phone_alter_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='bargarh', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Odisha', max_length=300),
            preserve_default=False,
        ),
    ]
