# Generated by Django 5.1.6 on 2025-05-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_useraccount_age_useraccount_dob_useraccount_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dob',
        ),
    ]
