# Generated by Django 5.1.6 on 2025-05-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_address_main_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='main',
        ),
    ]
