# Generated by Django 5.1.6 on 2025-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_remove_address_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=100),
        ),
    ]
