# Generated by Django 5.1.6 on 2025-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportfilter',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='reportfilter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topproductreport',
            name='revenue_report',
        ),
        migrations.RemoveField(
            model_name='topproductreport',
            name='product',
        ),
        migrations.DeleteModel(
            name='MonthlyRevenueComparison',
        ),
        migrations.DeleteModel(
            name='ReportFilter',
        ),
        migrations.DeleteModel(
            name='RevenueReport',
        ),
        migrations.DeleteModel(
            name='TopProductReport',
        ),
    ]
