# Generated by Django 5.1.6 on 2025-05-11 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_revenue_remove_reportfilter_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='month',
            field=models.DateField(editable=False, help_text='First day of the month this revenue belongs to', null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
