# Generated by Django 5.1.6 on 2025-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_alter_revenue_options_revenue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={},
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='month',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='value',
        ),
        migrations.AddField(
            model_name='revenue',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
