# Generated by Django 5.1.6 on 2025-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_cart_status_alter_cart_user_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.CharField(max_length=15),
        ),
    ]
