# Generated by Django 5.1.6 on 2025-04-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_shiprocketorder_status_code_and_more'),
        ('Orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedcartitem',
            name='ordered_cart',
        ),
        migrations.RemoveField(
            model_name='orderedcartitem',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='OrderedCart',
        ),
        migrations.DeleteModel(
            name='OrderedCartItem',
        ),
    ]
