# Generated by Django 5.1.6 on 2025-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_cartitem_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=464684568489, editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
