# Generated by Django 5.1.6 on 2025-04-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_rename_total_price_order_sub_total_order_cod_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('SHIPMENT_CREATED', 'SHIPMENT_CREATED')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], default='PROCESSING', max_length=30),
        ),
    ]
