# Generated by Django 5.1.6 on 2025-04-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_order_status_alter_orderhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='total_price',
        ),
    ]
