# Generated by Django 5.1.6 on 2025-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='content_type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.CharField(db_index=True, default='anish', max_length=20),
            preserve_default=False,
        ),
    ]
