# Generated by Django 5.1.6 on 2025-04-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_remove_orderhistory_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='disccount',
            new_name='discount',
        ),
    ]
