# Generated by Django 5.1.6 on 2025-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_rename_disccount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='additional_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
