# Generated by Django 5.1.6 on 2025-04-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_orderhistory_additional_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistoryitem',
            name='tax',
        ),
    ]
