# Generated by Django 5.1.6 on 2025-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_remove_orderhistoryitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
