# Generated by Django 5.1.6 on 2025-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_orderedcart_orderedcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(default='TEST', max_length=500),
            preserve_default=False,
        ),
    ]
