# Generated by Django 5.1.6 on 2025-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_order_total_price_orderhistory_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ORDERED', 'ORDERED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=10),
        ),
    ]
