# Generated by Django 5.1.6 on 2025-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ORDERED', 'ORDERED')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('CANCELED', 'CANCELED'), ('SHIPMENT_CREATED', 'SHIPMENT_CREATED')], default='ORDERED', max_length=30),
        ),
    ]
