# Generated by Django 5.1.6 on 2025-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_order_shiprocket_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiprocket_order_id',
        ),
        migrations.AddField(
            model_name='orderedcart',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
