# Generated by Django 5.1.6 on 2025-05-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_alter_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
