# Generated by Django 5.1.6 on 2025-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_address_name',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_city',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_contact_no',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_district',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_house_no',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_locality',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_pincode',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_state',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rcv_street',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_address_name',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_city',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_contact_no',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_district',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_house_no',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_locality',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_pincode',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_state',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='rcv_street',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
